# Generated by Django 3.2.9 on 2021-11-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_pregnant',
            field=models.DateTimeField(blank=True, default='2020-11-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_pregnant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_week_pregnant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
