# Generated by Django 3.2.9 on 2021-11-14 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211114_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_pregnant',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
