# Generated by Django 3.2.9 on 2021-11-13 22:14

from django.db import migrations, models
import notifcation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notefication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notfication', models.CharField(max_length=200)),
                ('content_note', models.TextField(max_length=2500)),
                ('number_week', models.IntegerField()),
                ('number_month', models.IntegerField()),
                ('img_note', models.ImageField(upload_to=notifcation.models.impage_upload)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number_week'],
            },
        ),
    ]
