# Generated by Django 3.2.9 on 2021-11-13 21:10

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='visiting', to='accounts.profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Image_visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_visiting', models.ImageField(upload_to=home.models.impage_upload)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('visiting', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='image_visting', to='home.visiting')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
