# Generated by Django 3.2.9 on 2021-11-16 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_image_visiting_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_visiting',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visiting',
            name='id',
        ),
        migrations.AddField(
            model_name='image_visiting',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='visiting',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
