# Generated by Django 3.2.9 on 2021-11-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211116_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_visiting',
            name='visiting',
            field=models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, related_name='image_visting', to='home.visiting'),
        ),
    ]
