# Generated by Django 3.2.9 on 2021-11-16 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_image_visiting_visiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_visiting',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
