# Generated by Django 3.2.9 on 2021-11-16 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211116_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_visiting',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image_visiting',
            name='visiting',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='image_visting', to='home.visiting'),
        ),
        migrations.AlterField(
            model_name='visiting',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
